<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">

	<title>Individual Reflections</title>
	<meta name="description" content="">
	<meta name="author" content="">

	<link rel="stylesheet" href="css/style.css">

	<!--Import from Google Fonts: -->
	<link rel="preconnect" href="https://fonts.gstatic.com">
	<link href="https://fonts.googleapis.com/css2?family=Merriweather:ital,wght@0,300;0,400;1,300&family=Poppins&display=swap" rel="stylesheet">

	<link rel="favicon" href="images/favicon.png">

	<style>
	p    {text-align: justify;}
	.tab {
		display: inline-block;
    margin-left: 40px;}
	</style>

</head>

<body>
	<header>
		<h1>Individual Reflections</h1>
	</header>
	<nav>
		<ul>
			<li><a href="index.php" title="Home">Home</a></li>
			<li><a href="test-start.php" title="Start the test">Start Test</a></li>
			<li><a href="results-summary.php" title="Summary of All Results">Summary of All Results</a></li>
			<li><a href="group-reflection.php" title="Group Reflection">Group Reflection</a></li>
			<li><a href="individual-reflection.php" title="Individual Reflections">Individual Reflections</a></li>
		</ul>
	</nav>

	<main>
	    <p>Jump to Specific Individual Reflection:</p>
	    <ul style="text-align:left;margin-left:15%;">
	        <li><a href="#pettis">Ben Pettis</a></li>
	        <li><a href="#liu">Rena Liu</a></li>
	        <li><a href="#schilling">Jacob Schilling</a></li>
	        <li><a href="#wei">Yiheng Wei</a></li>
	    </ul>
	    <hr />
		<h3 id="pettis">Ben Pettis</h3>
		<p><span class="tab"></span>Throughout the past several years, much of my coursework has pushed me to think critically about the societal effects of media. And while I feel confident in my ability to analyze and critique power structures within and surrounding new media technology, I was always somewhat dissatisfied in the singular focus on pointing out problems without offering much by way of potential solutions. Thus, when I had the opportunity to take this course, I was excited by the opportunity to explore ways to develop websites that attempt to address systemic inequality and implicit biases. When I first read about the final project guidelines toward the beginning of the semester, I was admittedly somewhat intimidated given my general lack of development experience. Nevertheless, I viewed the chance to create an alternative implicit bias test as a unique opportunity to push back against what I had been only critiquing for many years before this.</p>
		<p><span class="tab"></span>My personal goals with this project were twofold. First, I wanted to hone and practice my skills working with PHP and mySQL. Second, I wanted to experiment with new methods of attempting to “measure” bias. I knew that our test could not claim to truly measure bias, but I did see it as an chance to try and raise awareness of implicit biases without similar negative experiences. By measuring user input in a more indirect fashion, along with providing adequate context in the results, my hope was that we could present the issues of implicit biases to our users, but without delivering results in as much of a “prescriptive” or diagnostic fashion.</p>
		<p><span class="tab"></span>My role in the group ended up being primarily focused on back-end development—including database structure and PHP scripting, while the others in the group helped produce the specific content and formatted the page display for end users. I began by creating some basic PHP pages that would form the structure of the test. In addition to basic HTML form functionalities, our website measures the word count of the user input, as well as records the amount of time they spend on each page.</p>
		<p><span class="tab"></span>I was able to develop a basic word counter based on tutorials and examples that I read from Stack Exchange. Our website uses JavaScript to count the number of words that have been typed into the text fields, and then displays this word count on the page for the viewer to have a sense of how much they have written. As many people rightly point out, there are many drawbacks to using JavaScript, a client-side scripting language, for this functionality. Anything that runs client-side is more vulnerable to being modified. It would be theoretically possible for a user to modify the script to report an inaccurate word count. Best practices would be to use JavaScript to display the word count to the user while they are typing, but then perform server-side verification before storing the word count in the database. However, this would require us to send the response data back to the server, which present both privacy concerns as well as creates risk of SQL injection exploits. For this initial phase of the project, I determined that trusting the client-side code was an acceptable risk.</p>
		<p><span class="tab"></span>Next, I developed functionality to measure the amount of time that a user spent on each page. I believe that this measurement is one of the primary features that sets our implicit bias apart from a mere survey. By measuring the amount of time a user spends on each page, we are indirectly measuring how long it took them to make a guilty/innocent determination on each page. While we do not associate these times with any specific meaning (e.g. a certain time correlates to a certain level of bias), we do allow the user to compare their times on the photos to the time it took to describe themselves as one opportunity to consider how they might inadvertently make assumptions about other people they see. I created this functionality by using PHP’s microtime() function. This function will return the time in milliseconds past the epoch, or unix timestamp. By recording microtime() when the page is first loaded and comparing it to microtimetime() when the form is submitted, we can do basic subtraction to count the number of seconds that the user spend on the page. Then, we simply convert into seconds to display to the user. </p>
		<p><span class="tab"></span>My other major contribution to the project was creating the database structure to store our test results. The data structure that we are using on the website is simpler than what is ideal, or based on best practices. We are using a single mySQL table to store all of the results from the test. This means that multiple types of responses (self-description, photo description times, and similarity scores) all in the same table. While the functionality works, this is not ideal for efficient data organization nor for future expandability. I believe that it would have been more ideal to create a separate database for the test, with individual tables for questions, description times, and similarity scores. This would likely make it easier to query specific data types for comparison and analysis, as well as would make it easier to add additional questions or replace photos. However, I felt it was appropriate to use a simpler database structure to minimize issues when migrating from my local testing environment to the production server. Especially given that the group did not all have access to the same testing environment, I wanted to minimize the potential to accidentally break something in production.</p>
		<p><span class="tab"></span>This somewhat inefficient data structure can be understood as a direct result of our remote-based development environment and working set up. Because of the COVID-19 pandemic, we were unable to meet face-to-face, and we were actually working across several time zones as well. This made it difficult to do any synchronous development, and instead we primarily worked asynchronously in separate parts. For example, once I had created the initial functionality, we were able to collaborate as a group to write the actual page content, determine how to phrase our questions, and finally formatting the pages in CSS. Thankfully, our group was able to use a semi-synchronous messaging platform to communicate effectively with one another. This was much more efficient than relying on email, for instance, given that we could send longer messages to be read later, but also were able to send shorter messages in-the-moment. </p>
		<p><span class="tab"></span>Ultimately, I am happy with our group’s organizational structure and system of working remotely with one another. Despite the challenges of remote collaboration, we were still able to produce a working web product in just a few week’s time—and, hopefully, it is at least somewhat successful at meeting our goals of raising awareness about implicit biases. I believe that our alternative implicit bias test not only demonstrates the ability to develop a product even while working remotely, but also synthesizes many of the concepts from the course and reminds us that in addition to critiquing systems of inequality in technology, we do not necessarily have to adopt a wholly cynical view. Our project demonstrates that it is possible to also push back against structural issues and attempt to create more just alternatives. </p>
		<hr />

		<h3 id="liu">Rena Liu</h3>
		<p><span class="tab"></span>The final project in LIS500 made me realize that the remote-paired programming session requires teamwork and communication. My group and I made a Facebook group chat on Messenger to thoroughly discuss with each other what to do, what we have done, and any other questions that we had. Communication is key for remote work, especially programming. Sometimes it was difficult to assign each other tasks, so we took the initiative to give ourselves our own missions to do for the project. I worked on the group reflection, reflective questions, photo discoveries, and feedback incorporation. These tasks all happened as we discussed our topic and slowly defined the test as a whole. However, coding was hard to split upon as there was no system where we could all code at the same time without interrupting each other. Using Bluehost did minimize issues of a shared project, but having the possibility of doing the coding work together at the same time would be even better. If only there was a way to somehow incorporate the same idea of “working together at a computer lab” like before the pandemic happened. Because there are four of us, our schedules are very different from one another so we did our work at our own available times. Fortunately, there were many lectures and readings that could assist us in the use of Bluehost and MAMP for the project to go smoothly.</p>
        <p><span class="tab"></span>For my tasks specifically, I discussed with my teammates what kind of test we should do. We wanted to use visuals as our main questions to get unique results and interpretations. Therefore, I found ten images of actual criminals or those who have been innocently accused so that we could provide an accurate description of each crime. After this, I did some research for our five self-reflection questions that were related between personality/characteristics and crime. There is a lot of studies on this topic and it was easy to formulate indirect questions that would be too obvious while taking the test. Then after we got our peers’ feedbacks, I made a list of adjustments that we needed to make on our test. I made the test shorter from ten images to six along with the adjustment of our “results” page. Many individuals complained about repetitiveness and how it was too long. Thus, by almost reducing the questionnaire by half, it should give us enough space to incorporate the ideas we wanted while making it an easier test for the users to take. Another important idea was to provide more background information about the person’s case. So, I gathered the short and concise case descriptions and labeled each photo with their respective case. Finally, I helped with the group reflection where we described our choices on making the test and its goals. The project overall gave me more insight into how to succeed in remote-programming work and regarding implicit biases (due to our results).</p>
		<p><span class="tab"></span>I enjoyed the course’s content throughout the semester as it made me reflect on my unconscious actions/thoughts and improve my coding in HTML and PHP. I believe that the discussions were a wonderful way to have us interact with each other while also talking about a deep topic with new perspectives. This class is thoughtfully different from my other computer science classes as it focused more on the history and background of the tech field rather than simply coding for the entire semester instead. I would definitely recommend this course to those in my major as it brings in a new perspective for tech and initiates conversations that need to occur for educational purposes. Overall, I learned a lot from this course and it will help me in my future endeavors within the computer science field.</p>
		<p><a href="#top">Back to Top of Page</a></p>
		<hr />

		<h3 id="schilling">Jacob Schilling</h3>
		<p><span class="tab"></span>In regard to the content we needed to code, this final project was a little different from the other projects and made some of that coordination more difficult. Before we needed to make our own little website page and then coordinate on the index. In something like this it was difficult to split things up into separate parts since there was so much overlap and data that needed to be transferred across the pages. Also, Ben was just too fast at the coding, and had a great website up and running almost immediately after we discussed the test we wanted to perform.</p> 
        <p><span class="tab"></span>Since the website was pretty much flawless in the first iteration, my contributions had to come in other ways. I helped with some of the CSS, the initial feedback (from group members and classmates), data analysis ideas and bug finding. We were not really designating tasks amongst the group either, so everyone was volunteering for their own parts to help the project. After the initial frame of the website was done, I touched up a few of the alignments on the pages and other minor changes.</p> 
        <p><span class="tab"></span>A lot the work was also done in the background, during the idea generation phase. We discussed whether descriptions of the crime were necessary, how many questions would the user be willing to answer, and how did we want the data to be displayed/interpreted. I also suggested putting up two different pictures of a person, one in a mugshot the other not. This idea did not come through in the final design plan, since we were already collecting a lot of information and were asking a lot of questions.</p> 
        <p><span class="tab"></span>When Yiheng first took the test in its earliest stages she brought up the point that we did not have much diversity in the gender of the people we were displaying. The initial count was nine men and one woman. So, I went about on a search finding people who fit our test to even that out to 5-5 and putting the new people into the current test. Another area of feedback we received was that ‘it would be nice to know a little more about each case’. So, I also wrote up some short and broad descriptions of the crime each person was accused of. We wanted to get that information out there to those taking the test but wanted to make sure it did not affect their decisions. After taking into all the feedback and implementing it, I tested all the aspects of the test. When we had condensed the questions down, an error had occured that the data from the last question was not transferring, so I dove into the code on page six and got it back up and functioning.</p>
        <p><span class="tab"></span>One of the most interesting parts about this test was the information we collected, and how it was used to invoke questions rather than provide a number or specific answer. Since we are not experts in the subject, we based our site on it would have been difficult for us to assign a value to something. The questions really get the user to inwardly think about why they responded the way they did, rather than them getting that brief categorical answer.</p>
        <p><span class="tab"></span>Overall, this class got me to grow in HTML, PHP, and CSS all of which I had never touched before in my life (except when doing a minor visual change with the inspect tool). I also gained a much deeper understanding of the long stemming issues affecting minorities in the tech industry. I had only briefly learned about the issues before when talking about insurance and machine learning.</p>
</p>
		<p><a href="#top">Back to Top of Page</a></p>
		<hr />
		
		<h3 id="wei">Yiheng Wei</h3>
		<p><span class="tab"></span>Throughout this project, I found that one of the challenges of remote cooperation for me was communication. Even though I was able to gather teammates together and create a group chat via Messager in early April, I forgot to check the messages there for the next couple of days. Due to the Great Firewall in China, I have to connect to a VPN before I can log in to Facebook and receive messages. However, it was clear that I failed to do so at the beginning of the project. As a result, I missed the brainstorm of the test's format, and I apologized for not being able to participate in the discussion. This incident reminded me that it was my responsibility to keep track of the messages and follow up with the project progress. After then, I tried to check on the group chat after I got up every day. Sometimes my teammates already had some initial thoughts while I was asleep, and I would help implement these ideas on the website. At other times I could also contribute to the discussion.</p>
		<p><span class="tab"></span>Overall, for the final project, I was responsible for testing the website's functionalists, offering suggestions for the bias test, and unifying the style of the web pages. I discussed with my teammates what I learned from the test and what could be improved. Specifically, I talked about that I tended to have a bias towards people who look like me, i.e., Asian females. Although the test itself only contained two female photos out of 10, I found that gender was an essential indicator that influenced my choices. After a short discussion, we decided to increase the number of photos of female suspects so that the test kept a balance of gender, age, and ethnicity. Besides this, I also helped organize the web pages and implement the group discussion to the website.</p>
		<p><span class="tab"></span>Through the process of pair design, I got to practice several skills such as coding, communication, and cooperation. Working in a group allowed us to learn from each other and see things from different perspectives. Besides the final project, we had several opportunities to meet new people and interact with them. Even though this is an asynchronous class and our classmates are all around the world, we are connected through the internet. The course provides a platform for us to share information and learn from each other. I also made friends with classmates who had the same major as me and shared similar interests.</p>
		<p><span class="tab"></span>In the past three months, we read lots of articles and watched lectures about the issues in the tech world today. The development of science and technology is joyful, but it also comes with the further deepening of discrimination and oppression. Seeing the disadvantages of technology and its negative influence on our society, we become more critical about the information we receive and the algorithms we use. For future coders and people who want to work in this industry, we also have a deeper understanding of our responsibility to promote greater equality using our abilities.</p>
		<p><a href="#top">Back to Top of Page</a></p>
		<hr />

		<p style="text-align: center;">Return to the <a href="index.php" title="Home Page">Home Page</a>
	</main>

	<footer>
		&copy; <?php echo date('Y') ?>


		<?php $mysqli->close(); ?>
	</footer>
</body>
</html>
